AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"
Bundler/OrderedGems:
  Enabled: false
Metrics/MethodLength:
  Max: 20
