name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build --target=ci --tag=ghcr.io/adamniedzielski/happy_news .
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image
      run: docker push ghcr.io/adamniedzielski/happy_news

  test:
    needs: build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:

    - name: Run Rubocop
      run: |
        docker run happy_news bundle exec rubocop
    - name: Run tests
      run: |
        docker run --add-host=host.docker.internal:host-gateway --env DATABASE_HOST=host.docker.internal --env DATABASE_USERNAME=postgres --env GMAIL_USERNAME=${{ secrets.GMAIL_USERNAME }} happy_news bundle exec rails db:setup spec
