name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build --target=ci --tag=happy_news .
    - name: Run Rubocop
      run: |
        docker run happy_news bundle exec rubocop
    - name: Run tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
      run: |
        bundle exec rails db:setup
        bundle exec rails spec
