name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/adamniedzielski/happy_news:latest
          target: ci
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/adamniedzielski/happy_news:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT_TOKEN }}
    env:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
    services:
      postgres:
        image: postgres:11.6-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Run Rubocop
        run: |
          bundle exec rubocop
        working-directory: /happy_news
      - name: Run tests
        run: |
          bundle exec rails db:setup spec
